version: '3.8'

services:
  nn-frontend:
    restart: always
    depends_on:
      nn-models:
        condition: service_healthy

  nn-models:
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000/_health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
